/**
 *
 * @author Asena Şahin, Halil Onur Fedai, Burak Alaydın, Barış Can
 */

package javaprogramminggame.VIEW;

import javax.swing.JButton;
import javax.swing.JLabel;

public class LeaderBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeaderBoardPanel
     */
    public LeaderBoardPanel() {
        initComponents();
    }
    
    public JButton getBackButton(){
        return backButton;
    }
    
    public JLabel getLB1(){
        return lb1;
    }
    
    public JLabel getLB2(){
        return lb2;
    }
    
    public JLabel getLB3(){
        return lb3;
    }
    
    public JLabel getLB4(){
        return lb4;
    }
    
    public JLabel getLB5(){
        return lb5;
    }

    public JLabel getLB11(){
        return lb11;
    }
    
    public JLabel getLB22(){
        return lb22;
    }
    
    public JLabel getLB33(){
        return lb33;
    }
    
    public JLabel getLB44(){
        return lb44;
    }
    
    public JLabel getLB55(){
        return lb55;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb0 = new javax.swing.JLabel();
        lb00 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        lb22 = new javax.swing.JLabel();
        lb33 = new javax.swing.JLabel();
        lb44 = new javax.swing.JLabel();
        lb55 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        backButton.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        backButton.setText("BACK");
        backButton.setMaximumSize(new java.awt.Dimension(200, 100));
        backButton.setMinimumSize(new java.awt.Dimension(200, 100));
        backButton.setPreferredSize(new java.awt.Dimension(200, 100));
        backButton.setSize(new java.awt.Dimension(200, 100));

        lb1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 0, 0));
        lb1.setText("1) -");
        lb1.setMaximumSize(new java.awt.Dimension(400, 100));
        lb1.setMinimumSize(new java.awt.Dimension(400, 100));
        lb1.setPreferredSize(new java.awt.Dimension(400, 100));
        lb1.setSize(new java.awt.Dimension(400, 100));

        lb2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 0, 0));
        lb2.setText("2) -");
        lb2.setMaximumSize(new java.awt.Dimension(400, 100));
        lb2.setMinimumSize(new java.awt.Dimension(400, 100));
        lb2.setPreferredSize(new java.awt.Dimension(400, 100));
        lb2.setSize(new java.awt.Dimension(400, 100));

        lb3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 0, 0));
        lb3.setText("3) -");
        lb3.setMaximumSize(new java.awt.Dimension(400, 100));
        lb3.setMinimumSize(new java.awt.Dimension(400, 100));
        lb3.setPreferredSize(new java.awt.Dimension(400, 100));
        lb3.setSize(new java.awt.Dimension(400, 100));

        lb4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 0, 0));
        lb4.setText("4) -");
        lb4.setMaximumSize(new java.awt.Dimension(400, 100));
        lb4.setMinimumSize(new java.awt.Dimension(400, 100));
        lb4.setPreferredSize(new java.awt.Dimension(400, 100));
        lb4.setSize(new java.awt.Dimension(400, 100));

        lb5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 0, 0));
        lb5.setText("5) -");
        lb5.setMaximumSize(new java.awt.Dimension(400, 100));
        lb5.setMinimumSize(new java.awt.Dimension(400, 100));
        lb5.setPreferredSize(new java.awt.Dimension(400, 100));
        lb5.setSize(new java.awt.Dimension(400, 100));

        lb0.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb0.setForeground(new java.awt.Color(51, 51, 51));
        lb0.setText("EASY");
        lb0.setMaximumSize(new java.awt.Dimension(400, 100));
        lb0.setMinimumSize(new java.awt.Dimension(400, 100));
        lb0.setPreferredSize(new java.awt.Dimension(400, 100));
        lb0.setSize(new java.awt.Dimension(400, 100));

        lb00.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb00.setForeground(new java.awt.Color(51, 51, 51));
        lb00.setText("HARD");
        lb00.setMaximumSize(new java.awt.Dimension(400, 100));
        lb00.setMinimumSize(new java.awt.Dimension(400, 100));
        lb00.setPreferredSize(new java.awt.Dimension(400, 100));
        lb00.setSize(new java.awt.Dimension(400, 100));

        lb11.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb11.setForeground(new java.awt.Color(255, 0, 0));
        lb11.setText("1) -");
        lb11.setMaximumSize(new java.awt.Dimension(400, 100));
        lb11.setMinimumSize(new java.awt.Dimension(400, 100));
        lb11.setPreferredSize(new java.awt.Dimension(400, 100));
        lb11.setSize(new java.awt.Dimension(400, 100));

        lb22.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb22.setForeground(new java.awt.Color(255, 0, 0));
        lb22.setText("2) -");
        lb22.setMaximumSize(new java.awt.Dimension(400, 100));
        lb22.setMinimumSize(new java.awt.Dimension(400, 100));
        lb22.setPreferredSize(new java.awt.Dimension(400, 100));
        lb22.setSize(new java.awt.Dimension(400, 100));

        lb33.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb33.setForeground(new java.awt.Color(255, 0, 0));
        lb33.setText("3) -");
        lb33.setMaximumSize(new java.awt.Dimension(400, 100));
        lb33.setMinimumSize(new java.awt.Dimension(400, 100));
        lb33.setPreferredSize(new java.awt.Dimension(400, 100));
        lb33.setSize(new java.awt.Dimension(400, 100));

        lb44.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb44.setForeground(new java.awt.Color(255, 0, 0));
        lb44.setText("4) -");
        lb44.setMaximumSize(new java.awt.Dimension(400, 100));
        lb44.setMinimumSize(new java.awt.Dimension(400, 100));
        lb44.setPreferredSize(new java.awt.Dimension(400, 100));
        lb44.setSize(new java.awt.Dimension(400, 100));

        lb55.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb55.setForeground(new java.awt.Color(255, 0, 0));
        lb55.setText("5) -");
        lb55.setMaximumSize(new java.awt.Dimension(400, 100));
        lb55.setMinimumSize(new java.awt.Dimension(400, 100));
        lb55.setPreferredSize(new java.awt.Dimension(400, 100));
        lb55.setSize(new java.awt.Dimension(400, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel lb0;
    private javax.swing.JLabel lb00;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb22;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb33;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb44;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb55;
    // End of variables declaration//GEN-END:variables
}
