/**
 *
 * @author Asena Şahin, Halil Onur Fedai, Burak Alaydın, Barış Can
 */

package javaprogramminggame.VIEW;

import javax.swing.JButton;

public class MainPagePanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPagePanel
     */
    public MainPagePanel() {
        initComponents();
    }
    
    public JButton getNewGameButton(){
        return newGameButton;
    }
    public JButton getLoadGameButton(){
        return loadGameButton;
    }
    public JButton getLeaderBoardButton(){
        return leaderBoardButton;
    }
    public JButton getAboutUsButton(){
        return aboutUsButton;
    }
    public JButton getTrainGameButton(){
        return trainGameButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGameButton = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();
        leaderBoardButton = new javax.swing.JButton();
        aboutUsButton = new javax.swing.JButton();
        trainGameButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setRequestFocusEnabled(false);
        setSize(new java.awt.Dimension(1280, 720));

        newGameButton.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        newGameButton.setLabel("NEW GAME");
        newGameButton.setMaximumSize(new java.awt.Dimension(800, 100));
        newGameButton.setMinimumSize(new java.awt.Dimension(800, 100));
        newGameButton.setPreferredSize(new java.awt.Dimension(800, 100));
        newGameButton.setSize(new java.awt.Dimension(800, 100));

        loadGameButton.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        loadGameButton.setText("LOAD GAME");
        loadGameButton.setMaximumSize(new java.awt.Dimension(800, 100));
        loadGameButton.setMinimumSize(new java.awt.Dimension(800, 100));
        loadGameButton.setPreferredSize(new java.awt.Dimension(800, 100));
        loadGameButton.setSize(new java.awt.Dimension(800, 100));

        leaderBoardButton.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        leaderBoardButton.setText("LEADERBOARD");
        leaderBoardButton.setMaximumSize(new java.awt.Dimension(800, 100));
        leaderBoardButton.setMinimumSize(new java.awt.Dimension(800, 100));
        leaderBoardButton.setPreferredSize(new java.awt.Dimension(800, 100));
        leaderBoardButton.setSize(new java.awt.Dimension(800, 100));

        aboutUsButton.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        aboutUsButton.setText("ABOUT US");
        aboutUsButton.setMaximumSize(new java.awt.Dimension(800, 100));
        aboutUsButton.setMinimumSize(new java.awt.Dimension(800, 100));
        aboutUsButton.setPreferredSize(new java.awt.Dimension(800, 100));
        aboutUsButton.setSize(new java.awt.Dimension(800, 100));

        trainGameButton.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        trainGameButton.setText("TRAIN");
        trainGameButton.setMaximumSize(new java.awt.Dimension(800, 100));
        trainGameButton.setMinimumSize(new java.awt.Dimension(800, 100));
        trainGameButton.setPreferredSize(new java.awt.Dimension(800, 100));
        trainGameButton.setSize(new java.awt.Dimension(800, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaderBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(trainGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leaderBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutUsButton;
    private javax.swing.JButton leaderBoardButton;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton trainGameButton;
    // End of variables declaration//GEN-END:variables
}
