/**
 *
 * @author Asena Şahin, Halil Onur Fedai, Burak Alaydın, Barış Can
 */

package javaprogramminggame.VIEW;

import javax.swing.JButton;

public class TrainChooseTopicPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrainChooseTopicPanel
     */
    public TrainChooseTopicPanel() {
        initComponents();
    }

    public JButton getBackButton() {
        return backButton;
    }

    public JButton getT1b() {
        return t1b;
    }

    public JButton getT2b() {
        return t2b;
    }

    public JButton getT3b() {
        return t3b;
    }

    public JButton getT4b() {
        return t4b;
    }

    public JButton getT5b() {
        return t5b;
    }

    public JButton getT6b() {
        return t6b;
    }

    public JButton getT7b() {
        return t7b;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        t1b = new javax.swing.JButton();
        t2b = new javax.swing.JButton();
        t3b = new javax.swing.JButton();
        t4b = new javax.swing.JButton();
        t5b = new javax.swing.JButton();
        t6b = new javax.swing.JButton();
        t7b = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        backButton.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        backButton.setText("BACK");
        backButton.setMaximumSize(new java.awt.Dimension(200, 100));
        backButton.setMinimumSize(new java.awt.Dimension(200, 100));
        backButton.setPreferredSize(new java.awt.Dimension(200, 100));

        t1b.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        t1b.setText("LOGIC");
        t1b.setMaximumSize(new java.awt.Dimension(300, 75));
        t1b.setMinimumSize(new java.awt.Dimension(300, 75));
        t1b.setPreferredSize(new java.awt.Dimension(300, 75));

        t2b.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        t2b.setText("LOOPS");
        t2b.setMaximumSize(new java.awt.Dimension(300, 75));
        t2b.setMinimumSize(new java.awt.Dimension(300, 75));
        t2b.setPreferredSize(new java.awt.Dimension(300, 75));

        t3b.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        t3b.setText("FUNDEMENTALS");
        t3b.setMaximumSize(new java.awt.Dimension(300, 75));
        t3b.setMinimumSize(new java.awt.Dimension(300, 75));
        t3b.setPreferredSize(new java.awt.Dimension(300, 75));

        t4b.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        t4b.setText("STRING");
        t4b.setMaximumSize(new java.awt.Dimension(300, 75));
        t4b.setMinimumSize(new java.awt.Dimension(300, 75));
        t4b.setPreferredSize(new java.awt.Dimension(300, 75));

        t5b.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        t5b.setText("MATH");
        t5b.setMaximumSize(new java.awt.Dimension(300, 75));
        t5b.setMinimumSize(new java.awt.Dimension(300, 75));
        t5b.setPreferredSize(new java.awt.Dimension(300, 75));

        t6b.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        t6b.setText("ARRAY");
        t6b.setMaximumSize(new java.awt.Dimension(300, 75));
        t6b.setMinimumSize(new java.awt.Dimension(300, 75));
        t6b.setPreferredSize(new java.awt.Dimension(300, 75));
        t6b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6bActionPerformed(evt);
            }
        });

        t7b.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        t7b.setText("DATA");
        t7b.setMaximumSize(new java.awt.Dimension(300, 75));
        t7b.setMinimumSize(new java.awt.Dimension(300, 75));
        t7b.setPreferredSize(new java.awt.Dimension(300, 75));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t7b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t4b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t5b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t6b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t7b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t6bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6bActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton t1b;
    private javax.swing.JButton t2b;
    private javax.swing.JButton t3b;
    private javax.swing.JButton t4b;
    private javax.swing.JButton t5b;
    private javax.swing.JButton t6b;
    private javax.swing.JButton t7b;
    // End of variables declaration//GEN-END:variables
}
